// <auto-generated />
using System;
using ELKH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELKH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214005931_AddRolesSupport")]
    partial class AddRolesSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ELKH.Models.CartModel", b =>
                {
                    b.Property<int>("PkCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("PkCartId");

                    b.HasIndex("ProductPkProductId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ELKH.Models.CategoryModel", b =>
                {
                    b.Property<int>("PkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.Property<int>("PkContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegisiteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkContactId");

                    b.HasIndex("RegisiteredUserPkRegisteredUserId");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("ELKH.Models.OrderItemModel", b =>
                {
                    b.Property<int>("PkOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersPkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkOrderItemId");

                    b.HasIndex("OrdersPkOrderId");

                    b.HasIndex("ProductsPkProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.Property<int>("PkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactDetailPkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegisteredUserPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("PkOrderId");

                    b.HasIndex("ContactDetailPkContactId");

                    b.HasIndex("RegisteredUserPkRegisteredUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ELKH.Models.OrderStatusModel", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderStatusId");

                    b.HasIndex("FkOrderId")
                        .IsUnique();

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("ELKH.Models.ProductImageModel", b =>
                {
                    b.Property<int>("PkProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductImageURL")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductPkProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkProductImageId");

                    b.HasIndex("ProductPkProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.Property<int>("PkProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryPkCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkWishListId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WishListPkWishListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkProductId");

                    b.HasIndex("CategoryPkCategoryId");

                    b.HasIndex("WishListPkWishListId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ELKH.Models.ProductRatingModel", b =>
                {
                    b.Property<int>("PkRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsPkProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisteredUsersPkRegisteredUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkRatingId");

                    b.HasIndex("ProductsPkProductId");

                    b.HasIndex("RegisteredUsersPkRegisteredUserId");

                    b.ToTable("ProductRatings");
                });

            modelBuilder.Entity("ELKH.Models.RegisteredUserModel", b =>
                {
                    b.Property<int>("PkRegisteredUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkRegisteredUserId");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("ELKH.Models.TransactionModel", b =>
                {
                    b.Property<int>("PkTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactDetailPkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DeliberyFee")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkContactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PkTransactionId");

                    b.HasIndex("ContactDetailPkContactId");

                    b.HasIndex("FkOrderId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ELKH.Models.UserLogModel", b =>
                {
                    b.Property<int>("PkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FkEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogOutTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PkLogId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("ELKH.Models.UserProfileModel", b =>
                {
                    b.Property<string>("PkEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PkEmail");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.Property<int>("PkWishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkWishListId");

                    b.HasIndex("FkUserId")
                        .IsUnique();

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ELKH.Models.CartModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductPkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("Cart")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisiteredUser")
                        .WithMany("ContactDetails")
                        .HasForeignKey("RegisiteredUserPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisiteredUser");
                });

            modelBuilder.Entity("ELKH.Models.OrderItemModel", b =>
                {
                    b.HasOne("ELKH.Models.OrderModel", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersPkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.ProductModel", "Products")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductsPkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.HasOne("ELKH.Models.ContactDetailModel", "ContactDetail")
                        .WithMany("Orders")
                        .HasForeignKey("ContactDetailPkContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithMany("Orders")
                        .HasForeignKey("RegisteredUserPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ELKH.Models.OrderStatusModel", b =>
                {
                    b.HasOne("ELKH.Models.OrderModel", "Order")
                        .WithOne("OrderStatuses")
                        .HasForeignKey("ELKH.Models.OrderStatusModel", "FkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ELKH.Models.ProductImageModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductPkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.HasOne("ELKH.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryPkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.WishListModel", "WishList")
                        .WithMany("Products")
                        .HasForeignKey("WishListPkWishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("ELKH.Models.ProductRatingModel", b =>
                {
                    b.HasOne("ELKH.Models.ProductModel", "Products")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductsPkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUsers")
                        .WithMany("ProductRatings")
                        .HasForeignKey("RegisteredUsersPkRegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("RegisteredUsers");
                });

            modelBuilder.Entity("ELKH.Models.TransactionModel", b =>
                {
                    b.HasOne("ELKH.Models.ContactDetailModel", "ContactDetail")
                        .WithMany("Transactions")
                        .HasForeignKey("ContactDetailPkContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELKH.Models.OrderModel", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("ELKH.Models.TransactionModel", "FkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.HasOne("ELKH.Models.RegisteredUserModel", "RegisteredUser")
                        .WithOne("WishLists")
                        .HasForeignKey("ELKH.Models.WishListModel", "FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ELKH.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ELKH.Models.ContactDetailModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ELKH.Models.OrderModel", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderStatuses")
                        .IsRequired();

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("ELKH.Models.ProductModel", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductRatings");
                });

            modelBuilder.Entity("ELKH.Models.RegisteredUserModel", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ContactDetails");

                    b.Navigation("Orders");

                    b.Navigation("ProductRatings");

                    b.Navigation("WishLists")
                        .IsRequired();
                });

            modelBuilder.Entity("ELKH.Models.WishListModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
